// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUp = "up"

// Up mapped from table <up>
type Up struct {
	UID         int       `gorm:"column:uid;primaryKey" json:"uid"`
	LastScanned time.Time `gorm:"column:last_scanned;not null" json:"last_scanned"`
}

// TableName Up's table name
func (*Up) TableName() string {
	return TableNameUp
}
