// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID         int       `gorm:"column:uid;primaryKey" json:"uid"`
	LastScanned time.Time `gorm:"column:last_scanned;not null" json:"last_scanned"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
