// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRelation = "user_relations"

// UserRelation mapped from table <user_relations>
type UserRelation struct {
	ID       int `gorm:"column:id;primaryKey" json:"id"`
	From     int `gorm:"column:from;not null" json:"from"`
	To       int `gorm:"column:to" json:"to"`
	Relation int `gorm:"column:relation;not null" json:"relation"`
}

// TableName UserRelation's table name
func (*UserRelation) TableName() string {
	return TableNameUserRelation
}
