// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	Avid        int       `gorm:"column:avid;not null" json:"avid"` // av不是bv
	LastUpdated time.Time `gorm:"column:last_updated;not null;default:CURRENT_TIMESTAMP" json:"last_updated"`
	ID          int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
